services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ud-programacionavanzadawebapplication
    ports:
      - "5400:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql